- name: Configure the block explorer server
  hosts: 127.0.0.1
  connection: local
  roles:
    - common
    - ufw
    - supervisor
    - mongod
    - redis
    - nginx
    - application
    - configure-gamecreditsd
    - celery
  vars:
    - rpc_user: "1e772fd4-acaf-4a1a-9970-ff957dbf9b99"
    - rpc_password: "3ea23bcd-4312-47dc-8246-5a290dab6447"
    - rpc_port: 8332
    - code_dir: "/exploder"
    - log_dir: "{{ ansible_env.HOME }}/logs"
    - datadir_path: "{{ ansible_env.HOME }}/.gamecredits"
    - blocks_dir: "{{ ansible_env.HOME }}/.gamecredits/blocks"
    - exploder_conf_dir: "{{ ansible_env.HOME }}/.exploder"
    - syncer_cache_size: 1000
    - syncer_stream_sync_limit: 99
    - syncer_task_lock_timeout: 3600
    - sentry_logging: False
    - sentry_token1: ""
    - sentry_token2: ""
    - sentry_path: ""
    - bootstrap_dir: "{{ ansible_env.HOME }}/bootstrap"
    - ipify_url: "https://api.ipify.org/"
    - production: False
    - bootstrap_dir_server_path: "/bootstrap/"
    - game_price_url: "https://api.coinmarketcap.com/v1/ticker/gamecredits"
    - unspent_tracking: False
    - geo_ip_url: "https://freegeoip.net"
    - address_min_length: 26
    - address_max_length: 34
    - game_address_starts_with: ['G', '3']
    - sha256_hash_length: 64
